name: EasyCommands
author: iEpix
main: us.kpvpdev.easycommands.EasyCommands
version: '0.0.1'

commands:
  clearinventory:
    aliases: [clear, ci]
    description: Clear the inventory of a Player.
  echelp:
    description: Shows the main Help command for EasyCommands.
    aliases: [easyhelp]
  feed:
    description: Feeds the Player to full hunger.
  freeze:
    description: Freeze the Player.
  heal:
    description: Heals the Player to full health.
  weather:
    description: Set the weather in a World.
